- name: Setting port SSH
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Allow port in ufw
      shell: ufw allow 51522

    - name: Change SSH port
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Port "
        line: "Port 51522"

    - name: Disable SSH banner
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Banner "
        line: "Banner none"
        state: present

    - name: Prevent empty passwords
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitEmptyPasswords "
        line: "PermitEmptyPasswords no"
        state: present

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin "
        line: "PermitRootLogin no"
        state: present

    - name: Enforce SSH protocol 2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Protocol "
        line: "Protocol 2"
        state: present

    - name: Set logging level to VERBOSE
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?LogLevel "
        line: "LogLevel VERBOSE"
        state: present

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted