- name: Configure resolvconf and set nameservers
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install resolvconf package
      apt:
        name: resolvconf
        state: present
      retries: 5
      delay: 10
      register: apt_result
      until: apt_result is succeeded

    - name: Set nameservers in resolvconf configuration file
      blockinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        block: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
      notify: Update resolvconf

  handlers:
    - name: Update resolvconf
      command: resolvconf -u
