- name: Setting port SSH
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Allow port 2123 in ufw
      shell: ufw allow 2123

    - name: Change SSH port to 2123
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Port "
        line: "Port 2123"

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
