- name: Install and configure ClamAV on Ubuntu
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install ClamAV and Freshclam for virus definition updates
      apt:
        name:
          - clamav
          - clamav-freshclam
        state: present

    - name: Create log file if not already present
      command: touch /var/log/clamav/freshclam.log
      args:
        creates: /var/log/clamav/freshclam.log
      become: true

    - name: Ensure Freshclam logging is enabled and configured
      lineinfile:
        path: /etc/clamav/freshclam.conf
        regexp: '^#?UpdateLogFile'
        line: 'UpdateLogFile /var/log/clamav/freshclam.log'
      become: true

    - name: Enable ClamAV service to start on boot
      systemd:
        name: clamav-freshclam
        enabled: yes
        state: started

    - name: Stop clamav-freshclam service
      systemd:
        name: clamav-freshclam
        state: stopped
      ignore_errors: true

    - name: Update ClamAV virus definitions
      command: freshclam