- name: Block IPs using ipsum list with iptables and ipset
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - iptables
          - ipset
        state: present
        update_cache: yes

    - name: Flush the existing ipset set if it exists
      command: ipset flush ipsum
      ignore_errors: yes

    - name: Create ipset hash:ip set
      command: ipset create ipsum hash:ip
      args:
        creates: /etc/ipset/ipset.rules
      ignore_errors: yes

    - name: Download ipsum IP list
      get_url:
        url: https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt
        dest: /tmp/ipsum.txt
        mode: '0644'

    - name: Add IPs to ipset from ipsum.txt
      shell: |
        for ip in $(grep -v "#" /tmp/ipsum.txt | grep -v -E "\s[1-2]$" | cut -f 1); do
          ipset add ipsum $ip || true
        done
      args:
        executable: /bin/bash

    - name: Remove existing iptables rule for ipsum set
      command: iptables -D INPUT -m set --match-set ipsum src -j DROP
      ignore_errors: yes

    - name: Add iptables rule to drop traffic from ipsum set
      command: iptables -I INPUT -m set --match-set ipsum src -j DROP

    - name: Save iptables and ipset rules
      shell: |
        iptables-save > /etc/iptables/rules.v4
        ipset save > /etc/ipset/ipset.rules
      args:
        executable: /bin/bash